name: Unit & Integration Tests

on:
    pull_request:
        branches:
            - develop
        paths-ignore:
            - '*.md'
env:
    DATABASE_URL: postgres://postgres:mysecretpassword@localhost:5432/notifications

jobs:
    Build:
        name: Build Application
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
            - name: Checkout repo
              uses: actions/checkout@master

            - name: Generate .env files
              run: cp .env.example .env

            - name: Read .nvmrc
              id: nvm
              run: echo "name=NVMRC::$(cat .nvmrc)" >> $GITHUB_OUTPUT

            - name: Setup node
              uses: actions/setup-node@master
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Lint files
              run: yarn lint
              
            - name: Build application
              run: yarn build

            - name: Units Tests
              run: yarn jest --ci
