name: 'Protect main branch'

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - '*.md'
jobs:
    check_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Dump context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "${GITHUB_CONTEXT}"

            - name: Check if the pull request is coming from a release branch
              if: github.base_ref =='main' && !contains(github.head_ref, 'release')
              uses: actions/github-script@v3
              with:
                  script: |
                      core.setFailed('Only pr from release branch coulb be opened to be merged in main')
